-- MySQL Script generated by MySQL Workbench
-- Fri 05 Aug 2016 05:29:39 PM PDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema belt_exam_prep
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `belt_exam_prep` ;

-- -----------------------------------------------------
-- Schema belt_exam_prep
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `belt_exam_prep` DEFAULT CHARACTER SET utf8 ;
USE `belt_exam_prep` ;

-- -----------------------------------------------------
-- Table `belt_exam_prep`.`authors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `belt_exam_prep`.`authors` ;

CREATE TABLE IF NOT EXISTS `belt_exam_prep`.`authors` (
  `author_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `author_name` VARCHAR(255) NOT NULL COMMENT '',
  `created_at` DATETIME NOT NULL COMMENT '',
  `updated_at` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`author_id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `belt_exam_prep`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `belt_exam_prep`.`users` ;

CREATE TABLE IF NOT EXISTS `belt_exam_prep`.`users` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `first_name` VARCHAR(255) NOT NULL COMMENT '',
  `last_name` VARCHAR(255) NOT NULL COMMENT '',
  `email` VARCHAR(255) NOT NULL COMMENT '',
  `pw_hash` VARCHAR(255) NOT NULL COMMENT '',
  `updated_at` DATETIME NOT NULL COMMENT '',
  `created_at` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`user_id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `belt_exam_prep`.`books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `belt_exam_prep`.`books` ;

CREATE TABLE IF NOT EXISTS `belt_exam_prep`.`books` (
  `book_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `book_title` VARCHAR(255) NOT NULL COMMENT '',
  `created_at` DATETIME NOT NULL COMMENT '',
  `updated_at` DATETIME NOT NULL COMMENT '',
  `authors_author_id` INT(11) NOT NULL COMMENT '',
  `users_user_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`book_id`, `authors_author_id`)  COMMENT '',
  INDEX `fk_books_authors1_idx` (`authors_author_id` ASC)  COMMENT '',
  INDEX `fk_books_users1_idx` (`users_user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_books_authors1`
    FOREIGN KEY (`authors_author_id`)
    REFERENCES `belt_exam_prep`.`authors` (`author_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_books_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `belt_exam_prep`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `belt_exam_prep`.`reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `belt_exam_prep`.`reviews` ;

CREATE TABLE IF NOT EXISTS `belt_exam_prep`.`reviews` (
  `review_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `review_rating` INT(11) NOT NULL COMMENT '',
  `review_text` MEDIUMTEXT NOT NULL COMMENT '',
  `created_at` DATETIME NOT NULL COMMENT '',
  `updated_at` DATETIME NOT NULL COMMENT '',
  `books_book_id` INT(11) NOT NULL COMMENT '',
  `users_user_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`review_id`)  COMMENT '',
  INDEX `fk_reviews_users1_idx` (`users_user_id` ASC)  COMMENT '',
  INDEX `fk_reviews_books1_idx` (`books_book_id` ASC)  COMMENT '',
  CONSTRAINT `fk_reviews_books1`
    FOREIGN KEY (`books_book_id`)
    REFERENCES `belt_exam_prep`.`books` (`book_id`)
    ON DELETE NO ACTION,
  CONSTRAINT `fk_reviews_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `belt_exam_prep`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
